project:
  type: book

book:
  title: "Excel to R: A Survivor's Guide for the Corporate Environment"
  author: "Alejandro Hagan"
  date: "9/10/3"
  chapters:
    - part: "Introduction"
      chapters: 
        - index.qmd
        - intro.qmd
        - learningR.qmd
        - database.qmd
        - spark.qmd

bibliography: references.bib

format:
  html:
    theme:
     light: flatly
     dark: darkly
    output_dir: files
  pdf:
    documentclass: scrreprt

editor: source



