project:
  type: book
  output-dir: docs
  
book:
  title: "Excel to R: A Survivor's Guide for the Corporate Environment"
  author: "Alejandro Hagan"
  date: "9/10/3"
  chapters:
    - part: "Introduction"
      chapters: 
        - index.qmd
        - intro.qmd
        - learningR.qmd
        - database.qmd
        - interactions.qmd
        - many_models.qmd
    - part: "Misc"
      chapters: 
        - vim.qmd
        - github.qmd

bibliography: references.bib

format:
  html:
    theme:
     light: flatly
     dark: darkly
    freeze: true



