---
title: "time series"
---


# how to create aggreation fucntion

timetk::summarize_by_time(
.date_var=date column
.by= aggregation level
col_name=aggregation step (n())
across()
,.type=c("cieling,round,floor)
)



%


## how to create diagomics

 tk_summary_diagnostics()  gives summary satistics of how much difference betweeen the time series
 
##  how to pad time when there gaps in data series
-   use to fill gaps with values in your time series

pad_by_time(
.date_var=data colum
.by="day"
.pad_value=0


)



## plot times series
group_by() %>% ## how to facet
plot_time_series(
.data_Var
,value
,.color_bar=group_name # puts groups in color
,.facet_Vars=name ## also how to facet
,.smooth=TRUE (adds in polynominal regression)
,..smooth_period="30 days"
,.smooth_span= prop of data
,.interactive=FALSE # to create ggplot object



)


## Filter time series 

filter_by_time(
.date_var=data column
start_date=
end_date="end"  or date
)

## split into training and test set

you assign the split data to an object

 time_series_split(
 date_var=date colomns
 assess= "8 weeks"
 cumulaitve = TRUE  sets the previous as training, false means you need to select training set
)

then you use the tk_time_series_cv_plan()  and plot_time_Series_cv_plan() to see the training and test data 


## create different time series models

linear_reg(

)

prophet_reg(
) %>% 
set_engine("prophet")


how to use?

prophet_reg %>% 
set_engine("prophet") %>% 
fit(predition_Value ~ data_col
,new_data=training(splits))


## model time worfklow
creates table to hold various fitted models
model_time_table(
fitted_model_1
)

- applies fitted models against testing data
- .calabration_data has the results
- savve as calibration data
model_tbl %>% 
modeltime_calibrate(
new_data=testing(splits)

)

to see this in practice
calibration_tbl %>% 
modeltime_forecat(actual_Date=existing_tlb) %>% 
plot_modeltime_forecast()

## how to see forecasting accuracy

calibration_tbl %>% modeltime_accuracy


plot_seasonal_diagnotistic


## recipe

recipe(formula,training(splits)) %>% 
step_timeseries_Signature() %>%
step_normalize(index.num,_year) %>% 
step_dummy(all_ordinal)
prep()
%>% juice (applies to the training step)


## create model element

linear_reg()

## create a workflow object
save as worflow

workflow %>% 
add_model(model_spec) %>% 
add_reciept(reciepe-sepc) %>% 
fit(training(splits)) 

calibration obj
modeltime_table() %>% 
modeltime_Calibration(testing(splits))


calibration_obj %>% modeltime_accuracy

calibration_obj %>% 
modeltime_forecast(
new_Data=testing(splits)
actual_Data=origional_ttbl) %>% 
plot_modeltime_forecast()



)

## mode diagnosics
detect lagged fuctions
plot_acf_diagnoistcs(
.lags="1 year", 25:100,100
.ccf_vars=columns,
.show_ccf_vars-only=TRUe # ony cross correlations var
,.facet_ncol=number of column


)


## sesaonality

plot_seaonsal_diagnotistc(
feasture_set=c(hour,weekday)
.geom="violin"
)

## anolomy

plot_anomoly_diagomsitc(
.data_var=data_col
.alpha= .01 #change anonoly sensitivity
.max_anolomoies =.01 # peak anaolyies

)

## get anoly data
tk::anomoly_diaogasitc(
same as plot, gets data with anolmogies in it
)

## seasons decomposition
gives you what is seasonal vs trend vs adjjustment

useful to understand how anomoliges are being detcted
plot_stl_diagostics(


)
## uses linear regression

helps ot identify useful features

plot_time_series_regression(
.date_var=data column
.formula= value~ as.numeric(date_col)+
wday(date_col)+
month(date_col)
show_summary=TRUE
)


provides time based mutate over time windows this is like group_by + mutate
mutate_by_time(
.by="week"
,formula


transofmration

loglp - applies log
standarize_vec - standardize and centers


tk_index() creates index

tk_make_timeseries makes time table

tk_make_holiday_sequence(
year_start
year_end
clandar
) %>% 
tk_get_holiday_signature( converst to grid matrix)

makes future time series
ts_make_future_time_zeries

future_frame(
lengt_out=periods
)





)

)

date_col %-time% "1 day"

date_col %+time% "6 weeks"

hello are you today, i am doing well but this is a significant enough change that i do need to learn how to type all all over again which is frustrating. that being said, i have gotten  used to the left space bar button sooner that i thought.''
 hopefully this will improbe some of the ergonomiv issues that i have and make type muvh quivker and faaster than bebefore.i
 
 
 hello hwo are you today i am doing so well, now that ia  have typing with myleft
 
 



library(fpaR)
