---
title: "Graphics with ggplot2"
author: "Alejandro"
date: "11/21/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


setting github
use_git_config(user.name = "haganistic", user.email = "alejandro.hagan@outlook.com")


# Admin how to set up your working space

## Manipulating working directories

getwd()

setwd()

list.files(pattern=$^, recursive=T)


`.` is equal to your working director `getwd()`


## Creating folders & filing guidelines 

file.exists
dir.exists
basename("c:/filedir/file.txt") -> "file.txt
dirname("c:/filedir/file.txt")->

create.dir("./newdir")
file.create("filename.txt")
shell.exec("filename.txt")
filesstrings::move_file("c:home/filename.txt","c:newdir")
file.copy("filename", "destination")
file.rename(directory,"existing file name","new file name")
-if directory is blank will assume getwd()
file.choose()
base::unlink("filename", recursive=T)
-recursve must be T to delete directories

[Link to learn more](http://theautomatic.net/2018/07/11/manipulate-files-r/#:~:text=Files%20can%20be%20deleted%20with%20R%20using%20unlink.,parameter%20recursive%20%3D%20TRUE.%20%23%20delete%20a%20file)


## how to connect to github

while all this may seem to new, quite honestly its because we have never been told good versioning and collaboration practices so we are reliant on saving to a LAN system, amending the name with  versioning control


## push & committ and commenting


# How to manipulate & tidy data

## how to import data

read.csv()

read_csv()

fread()

## how to change column types





 



## how to create data
seq()
runif()
sample(data,# of times, replace,)
c()
data.frame()

## how to create data with basic loops / repitition

## types of data

vector
data.frame
list


## some base R basics that will be helpful to you as you read the forums



## how to import files

- by folder
- by website
- excel spreadsheet
- powerbi model
- 

### how to find files by their type

### how to append files together

### how to automate file importation 


## file column names

### how to change column names

#### statically


#### dynamically

#### best practices when naming columns

### how to change column types

#### statically

#### dynamically

### how to check data structure
-unique

### how to clean data



### how to shape data


### how to subset data


#### filter

dynamic

static

### select

dynamic

static

### grouby


### summarize


### mutate


### fill / blanks/ replace values


### recode


### pivot / unpivot


### merge


### iterate


- apply a single function (single input or multiple inputs) to every/ some/ based on criteria column and get its outputs into a data frame (to be accessed)

- apply a single function with multiple inputs

- apply a functions to nested data frames

### explatory analysis 

- start with variance analysis 





 
 
 